include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = GravitationPrefs

# Hier listen wir alle .m-Dateien auf, die wir in grafik_2.png sehen
GravitationPrefs_FILES = GRVRootListController.m GravDonationLinkCell.m GravSourceLinkCell.m KRLabeledSliderCell.m KRLinkCell.m KRTableCell.m KRTwitterCell.m PSGravityLinkCell.m
GravitationPrefs_INSTALL_PATH = /Library/PreferenceBundles
GravitationPrefs_FRAMEWORKS = UIKit Preferences
GravitationPrefs_CFLAGS = -fobjc-arc

include $(THEOS)/makefiles/bundle.mk
